apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default
resources:
  - deployment.yaml
images:
  - name: registry-1.docker.io/asdfkco/jenkinstest
    newName: registry-1.docker.io/asdfkco/jenkinstest
    newTag: latest
